doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '8.0'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        auto_mapping: true

        mappings:
            App\Domain\Entity:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Entity'
                prefix: App\Domain\Entity
                alias: App\Domain\Entity
