services:
  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./:/var/www/test-task
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./:/var/www/test-task
    depends_on:
      - mysql

  php-cli:
    build:
      context: docker/php-cli
    volumes:
      - ./:/var/www/test-task

  node:
    image: node:18.4.0-alpine
    working_dir: /app
    volumes:
      - ./:/app

  mysql:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  myadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 3000000000
    ports:
      - "${PHPMyAdmin_PORT}:80"
